CREATE TABLE PERSON(
    ID INTEGER AUTO_INCREMENT,
    AGE INTEGER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR
);


-- ONE_TO_ANY mapping

CREATE TABLE ORDERS(
    ID INT PRIMARY KEY,
    IS_PAID BOOLEAN
);

CREATE TABLE ORDER_FILE(
    ID INT,
    NAME VARCHAR,
    ORDER_ID INT REFERENCES ORDERS(ID)
);

CREATE TABLE PRODUCT(
    ID INT,
    NAME VARCHAR,
    ORDER_ID INT REFERENCES ORDERS(ID)
);

CREATE TABLE ORDER_ATTRIBUTES(
    ID INT,
    DESCRIPTION VARCHAR,
    CREATED_AT DATE,
    OWNER_ID INT,
    ORDER_ID INT REFERENCES ORDERS(ID)
);

-- Many-To-X mapping support

CREATE TABLE BOOK
(
    ID INT PRIMARY KEY,
    NAME VARCHAR,
    AMOUNT_OF_PAGES INT
);

CREATE TABLE BOOK_DETAILS
(
    ID INT,
    DESCRIPTION VARCHAR,
    WRITTEN_IN DATE,
    BOOK_ID INT REFERENCES BOOK(ID)
);

CREATE TABLE AUTHOR
(
    ID INT PRIMARY KEY,
    NAME VARCHAR,
    COUNTRY VARCHAR
);

CREATE TABLE AUTHORS_BOOKS
(
    AUTHOR_ID INT,
    BOOK_ID INT
);

INSERT INTO AUTHOR(ID, NAME, COUNTRY) VALUES (52, 'Name is not important', 'DRC');

COMMIT;